name: "Lint Python code"
on:
  push: # Only execute pipeline on push to main branch
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs: 
  test: # Name of the job
    runs-on : ubuntu-latest # The job will run on the latest version of Ubuntu
    steps: 
      - uses: actions/checkout@v4 
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.13" # Specify the Python version to use
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Launch the unit tests
        run: pytest